### ISSUE TITLE
[Suggestion] Job auto cancellation

### ISSUE THREAD

**Issue by ByteRaper** [figgyc/seedhelper2#2]
Usually it takes like max 1 minute to complete a job for me, but sometimes there are jobs that mine for over a hour without completion. I dont know if thats normal.

**Comment by figgyc** [comment]
jobs are already auto cancelled and it should cancel after an hour, are you timing it to be sure?

**Comment by ByteRaper** [comment]
I could swear it ran over an hour. Next time it will happen, i'll time it and report back.
Edit: Also noticed: If you requeue a job, your script doesn't kill bfcl.exe

**Comment by ByteRaper** [comment]
So it didnt happen untill now and I also made a small modification on your script, so that im on the safe side.
